edit_uri: edit/main

nav:
     - Overview: getting-started-overview.md
     - Module 1:
            - 1.1 What is SPREAD?: module-1/what-is-spread.md
            - 1.2 What is the Engineering Intelligence Graph?: module-1/what-is-eig.md
            - 1.3 Creating a Studio application: module-1/creating-a-studio-application.md
     - Module 2:
            - 2.1 Understanding the SPREAD information architecture: module-2/understanding-spread-information-architecture.md
            - 2.2 Querying SPREAD in Studio: module-2/querying-spread.md
            - 2.3 Creating a display application: module-2/creating-a-display-application.md
     - Module 3:
            - 3.1 Studio data visualizations: module-3/studio-data-visualizations.md
            - 3.2 Creating data visualizations: module-3/creating-data-visualizations.md
